refresh-token: "insert_here"
chat-bot:
  enabled: True
  save-chatlog: True
  online-message: "HumanDotExe online!"
  ignore-commands: []

stream-overlays:
  notifications:
    cooldown: 3
    block: []
    follow:
      message: "Thanks for the follow {name}"
    subscription:
      message: "Thanks for the sub {name}"
  chat:
    include-commands: False
    include-command-output: False
    message-stays-for: 60
    message-refresh-rate: 5
    max-number-of-messages: 10